export default {
    FONT_SIZE_EXTRA_SMALL:10,
    FONT_SIZE_SMALL: 12,
    FONT_SIZE_MEDIUM: 15,
    PRIMARY_BUTTON_COLOR:'#0d4c8c',
    PRIMARY_TEXT_COLOR: '#FFFFFF',
    PRIMARY_BACKGROUND_COLOR: '#FFFFFF',
    SECONDARY_TEXT_COLOR: '#606060',
    BORDER_COLOR:'#606060'
  };